### ISSUE TITLE
Menus to set keybindings

### ISSUE THREAD

**Issue by FichteFoll** [JonasPf/JumpTo#4]
With ST3 it's rather inconvenient to open the example settings in the `.sublime-package` archive, copy the contents and create a new file (and directory) for setting the key bindings. It's okay that you don't force your key bindings on all users, but you should consider making these steps a bit easier.

I recommend adding an `open_file` command to the menu in `Preferences -> Package Settings` (like manu other packages do) with the example file in the `contents` parameter (see http://docs.sublimetext.info/en/sublime-text-2/reference/commands.html).

**Comment by JonasPf** [comment]
Fixed
